"""empty message

Revision ID: eabe78a51759
Revises: d4600a4e57cc
Create Date: 2025-01-16 12:02:13.193701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eabe78a51759"
down_revision = "d4600a4e57cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "bot_modules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["modules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_modules")
    op.drop_table("bots")
    op.drop_table("modules")
    # ### end Alembic commands ###
